export const SYSTEM_CONSTANTS = {
  APP_NAME: 'WavyAssets Global Backend User Dashboard',
  DEFAULT_PAGE_SIZE: 25,
  MAX_PAGE_SIZE: 100,
  TIME_LOCK_HOURS: 48,
  TIME_LOCK_SIGNERS_REQUIRED: 2,
  TICKET_EXPIRATION_SECONDS: 120,
  JWT_ACCESS_EXPIRATION: '15m',
  JWT_REFRESH_EXPIRATION: '7d',
  RATE_LIMIT_PUBLIC: 10,
  RATE_LIMIT_AUTHENTICATED: 50,
} as const;

export const ERROR_CODES = {
  ERR_INTERNAL_SERVER: 'ERR_INTERNAL_SERVER',
  ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
  ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  ERR_FORBIDDEN: 'ERR_FORBIDDEN',
  ERR_NOT_FOUND: 'ERR_NOT_FOUND',
  ERR_CONFLICT: 'ERR_CONFLICT',
  ERR_UNPROCESSABLE: 'ERR_UNPROCESSABLE',
  ERR_DESTINATION_QUARANTINED: 'ERR_DESTINATION_QUARANTINED',
  ERR_LEDGER_IMBALANCE: 'ERR_LEDGER_IMBALANCE',
  ERR_INSUFFICIENT_FUNDS: 'ERR_INSUFFICIENT_FUNDS',
  ERR_INVALID_HANDOFF_TICKET: 'ERR_INVALID_HANDOFF_TICKET',
  ERR_CIRCUIT_BREAKER_ACTIVE: 'ERR_CIRCUIT_BREAKER_ACTIVE',
} as const;
