export type CustodyBadge = 'SOVEREIGN_CUSTODY' | 'EXTERNAL_WEB3' | 'STAKING_LOCKUP';

export interface CryptoHolding {
  symbol: string;
  name: string;
  enclave: string;
  custodyType: CustodyBadge;
  custodyLabel: string;
  balance: number;
  unit: string;
  entryPrice: number;
  spotPrice: number;
  unrealizedPnl: number;
  pnlPct: number;
  riskRating: string;
  stakingApy?: number;
}

export interface StockHolding {
  symbol: string;
  name: string;
  category: string;
  custodian: string;
  shares: number;
  entryMark: number;
  currentMark: number;
  unrealizedPnl: number;
  pnlPct: number;
  beta: number;
  dripEnabled: boolean;
  isPreIpo: boolean;
}

export interface OrderBookEntry {
  price: number;
  size: number;
  total: number;
  depthPct: number;
}

export interface DcaScheduleItem {
  id: string;
  asset: string;
  frequency: 'DAILY' | 'WEEKLY' | 'BI_WEEKLY' | 'MONTHLY';
  amountUsd: number;
  sourceAccount: string;
  nextExecution: string;
  active: boolean;
}

export interface WalletTransaction {
  id: string;
  timestamp: string;
  vertical: 'CRYPTO' | 'STOCKS' | 'REAL_ESTATE' | 'CASH' | 'FEE';
  type: 'DEPOSIT' | 'WITHDRAWAL' | 'SWAP' | 'DIVIDEND' | 'SWEEP';
  description: string;
  amountUsd: number;
  status: 'CLEARED' | 'PENDING' | 'SETTLING';
  reference: string;
}

export const CRYPTO_HOLDINGS_DATA: CryptoHolding[] = [
  {
    symbol: 'BTC',
    name: 'BITCOIN SOVEREIGN COLD VAULT',
    enclave: 'Geneva Bunker Alpha',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 42.5,
    unit: 'BTC',
    entryPrice: 62100.0,
    spotPrice: 89420.0,
    unrealizedPnl: 1161100.0,
    pnlPct: 43.99,
    riskRating: 'AA+',
  },
  {
    symbol: 'ETH',
    name: 'ETHEREUM STAKING VALIDATOR (LIDO / ROCKET)',
    enclave: 'Zurich Node 04',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 380.0,
    unit: 'ETH',
    entryPrice: 2840.0,
    spotPrice: 3410.5,
    unrealizedPnl: 216790.0,
    pnlPct: 20.09,
    riskRating: 'AAA',
    stakingApy: 3.82,
  },
  {
    symbol: 'SOL',
    name: 'SOLANA HIGH-YIELD VALIDATOR',
    enclave: 'Singapore SG-01',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 2400.0,
    unit: 'SOL',
    entryPrice: 135.0,
    spotPrice: 182.4,
    unrealizedPnl: 113760.0,
    pnlPct: 35.11,
    riskRating: 'AA',
    stakingApy: 7.42,
  },
  {
    symbol: 'USDC',
    name: 'USDC CIRCLE CASH TREASURY POT',
    enclave: 'New York NY-03',
    custodyType: 'EXTERNAL_WEB3',
    custodyLabel: 'Treasury Web3',
    balance: 1115337.5,
    unit: 'USDC',
    entryPrice: 1.0,
    spotPrice: 1.0,
    unrealizedPnl: 0.0,
    pnlPct: 0.0,
    riskRating: 'AAA',
    stakingApy: 5.2,
  },
  {
    symbol: 'AVAX',
    name: 'AVALANCHE SUBNET CORE ENCLAVE',
    enclave: 'Geneva Bunker Beta',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 8500.0,
    unit: 'AVAX',
    entryPrice: 24.5,
    spotPrice: 32.8,
    unrealizedPnl: 70550.0,
    pnlPct: 33.88,
    riskRating: 'A+',
    stakingApy: 5.9,
  },
  {
    symbol: 'BNB',
    name: 'BINANCE COIN SOVEREIGN RESERVE',
    enclave: 'Tokyo Enclave TK-01',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'BNB',
    entryPrice: 580.0,
    spotPrice: 620.4,
    unrealizedPnl: 0.0,
    pnlPct: 6.97,
    riskRating: 'AA',
    stakingApy: 4.15,
  },
  {
    symbol: 'XRP',
    name: 'RIPPLE INSTITUTIONAL ESCROW LEDGER',
    enclave: 'Zurich Vault 01',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'XRP',
    entryPrice: 0.54,
    spotPrice: 0.58,
    unrealizedPnl: 0.0,
    pnlPct: 7.41,
    riskRating: 'AA',
  },
  {
    symbol: 'ADA',
    name: 'CARDANO POOL VALIDATOR STAKE',
    enclave: 'Frankfurt Node 02',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'ADA',
    entryPrice: 0.35,
    spotPrice: 0.38,
    unrealizedPnl: 0.0,
    pnlPct: 8.57,
    riskRating: 'A+',
    stakingApy: 3.45,
  },
  {
    symbol: 'DOT',
    name: 'POLKADOT RELAY CHAIN VALIDATOR',
    enclave: 'London Enclave LD-02',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'DOT',
    entryPrice: 4.2,
    spotPrice: 4.65,
    unrealizedPnl: 0.0,
    pnlPct: 10.71,
    riskRating: 'AA',
    stakingApy: 11.8,
  },
  {
    symbol: 'LINK',
    name: 'CHAINLINK DECENTRALIZED ORACLE NODE',
    enclave: 'Geneva Node 07',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'LINK',
    entryPrice: 11.2,
    spotPrice: 12.85,
    unrealizedPnl: 0.0,
    pnlPct: 14.73,
    riskRating: 'AA',
    stakingApy: 4.9,
  },
  {
    symbol: 'NEAR',
    name: 'NEAR PROTOCOL SHARDING ENGINE',
    enclave: 'Zurich Alpha 03',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'NEAR',
    entryPrice: 4.5,
    spotPrice: 5.15,
    unrealizedPnl: 0.0,
    pnlPct: 14.44,
    riskRating: 'A+',
    stakingApy: 8.2,
  },
  {
    symbol: 'SUI',
    name: 'SUI NETWORK HIGH-THROUGHPUT STAKE',
    enclave: 'Singapore Enclave SG-03',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'SUI',
    entryPrice: 1.8,
    spotPrice: 2.15,
    unrealizedPnl: 0.0,
    pnlPct: 19.44,
    riskRating: 'AA',
    stakingApy: 6.8,
  },
  {
    symbol: 'APT',
    name: 'APTOS MOVE PARALLEL VALIDATOR',
    enclave: 'New York NY-01',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'APT',
    entryPrice: 8.1,
    spotPrice: 9.4,
    unrealizedPnl: 0.0,
    pnlPct: 16.05,
    riskRating: 'A+',
    stakingApy: 7.1,
  },
  {
    symbol: 'POL',
    name: 'POLYGON PROOF-OF-STAKE CORE',
    enclave: 'London LD-04',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'POL',
    entryPrice: 0.38,
    spotPrice: 0.42,
    unrealizedPnl: 0.0,
    pnlPct: 10.53,
    riskRating: 'AA',
    stakingApy: 5.6,
  },
  {
    symbol: 'OP',
    name: 'OPTIMISM SUPERCHAIN SETTLEMENT VAULT',
    enclave: 'Geneva Node 09',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'OP',
    entryPrice: 1.45,
    spotPrice: 1.72,
    unrealizedPnl: 0.0,
    pnlPct: 18.62,
    riskRating: 'AA',
  },
  {
    symbol: 'ARB',
    name: 'ARBITRUM ONE INSTITUTIONAL RESERVE',
    enclave: 'Zurich Vault 05',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'ARB',
    entryPrice: 0.52,
    spotPrice: 0.59,
    unrealizedPnl: 0.0,
    pnlPct: 13.46,
    riskRating: 'AA',
  },
  {
    symbol: 'ATOM',
    name: 'COSMOS HUB INTERCHAIN VALIDATOR',
    enclave: 'Frankfurt FR-01',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'ATOM',
    entryPrice: 4.8,
    spotPrice: 5.35,
    unrealizedPnl: 0.0,
    pnlPct: 11.46,
    riskRating: 'A+',
    stakingApy: 14.5,
  },
  {
    symbol: 'RENDER',
    name: 'RENDER NETWORK DECENTRALIZED GPU VAULT',
    enclave: 'Geneva Bunker Beta',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'RENDER',
    entryPrice: 5.6,
    spotPrice: 6.85,
    unrealizedPnl: 0.0,
    pnlPct: 22.32,
    riskRating: 'AA',
  },
  {
    symbol: 'INJ',
    name: 'INJECTIVE PROTOCOL ON-CHAIN DERIVATIVES',
    enclave: 'Singapore SG-02',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'INJ',
    entryPrice: 18.5,
    spotPrice: 22.1,
    unrealizedPnl: 0.0,
    pnlPct: 19.46,
    riskRating: 'A+',
    stakingApy: 12.4,
  },
  {
    symbol: 'TIA',
    name: 'CELESTIA DATA AVAILABILITY VALIDATOR',
    enclave: 'Zurich Node 08',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'TIA',
    entryPrice: 5.2,
    spotPrice: 6.15,
    unrealizedPnl: 0.0,
    pnlPct: 18.27,
    riskRating: 'A+',
    stakingApy: 10.9,
  },
  {
    symbol: 'FET',
    name: 'ARTIFICIAL SUPERINTELLIGENCE ALLIANCE',
    enclave: 'London LD-01',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'FET',
    entryPrice: 1.25,
    spotPrice: 1.48,
    unrealizedPnl: 0.0,
    pnlPct: 18.4,
    riskRating: 'A+',
    stakingApy: 6.2,
  },
  {
    symbol: 'ICP',
    name: 'INTERNET COMPUTER PROTOCOL NODE',
    enclave: 'Zurich HQ Data Enclave',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'ICP',
    entryPrice: 7.8,
    spotPrice: 8.95,
    unrealizedPnl: 0.0,
    pnlPct: 14.74,
    riskRating: 'AA',
    stakingApy: 13.8,
  },
  {
    symbol: 'FIL',
    name: 'FILECOIN INSTITUTIONAL STORAGE RESERVE',
    enclave: 'Geneva Freeport Vault',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'FIL',
    entryPrice: 3.4,
    spotPrice: 3.82,
    unrealizedPnl: 0.0,
    pnlPct: 12.35,
    riskRating: 'A+',
  },
  {
    symbol: 'LTC',
    name: 'LITECOIN LIQUID HARDENED VAULT',
    enclave: 'Zurich Vault 02',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'LTC',
    entryPrice: 68.0,
    spotPrice: 74.5,
    unrealizedPnl: 0.0,
    pnlPct: 9.56,
    riskRating: 'AA',
  },
  {
    symbol: 'KAS',
    name: 'KASPA GHOSTDAG ZERO-COLLISION VAULT',
    enclave: 'Geneva Bunker Alpha',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'KAS',
    entryPrice: 0.12,
    spotPrice: 0.15,
    unrealizedPnl: 0.0,
    pnlPct: 25.0,
    riskRating: 'A+',
  },
  {
    symbol: 'STX',
    name: 'STACKS BITCOIN LAYER-2 POOL',
    enclave: 'New York NY-02',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'STX',
    entryPrice: 1.6,
    spotPrice: 1.92,
    unrealizedPnl: 0.0,
    pnlPct: 20.0,
    riskRating: 'AA',
    stakingApy: 8.7,
  },
  {
    symbol: 'TON',
    name: 'THE OPEN NETWORK (TON) VALIDATOR POOL',
    enclave: 'Dubai DIFC Vault',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'TON',
    entryPrice: 4.8,
    spotPrice: 5.65,
    unrealizedPnl: 0.0,
    pnlPct: 17.71,
    riskRating: 'A+',
    stakingApy: 4.8,
  },
  {
    symbol: 'ALGO',
    name: 'ALGORAND PURE PROOF-OF-STAKE RESERVE',
    enclave: 'Zurich Node 06',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'ALGO',
    entryPrice: 0.11,
    spotPrice: 0.13,
    unrealizedPnl: 0.0,
    pnlPct: 18.18,
    riskRating: 'AA',
    stakingApy: 6.4,
  },
  {
    symbol: 'SEI',
    name: 'SEI NETWORK PARALLEL HIGH-FREQ STAKE',
    enclave: 'Tokyo TK-02',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'SEI',
    entryPrice: 0.34,
    spotPrice: 0.41,
    unrealizedPnl: 0.0,
    pnlPct: 20.59,
    riskRating: 'A+',
    stakingApy: 5.2,
  },
  {
    symbol: 'FTM',
    name: 'FANTOM SONIC SPEED VALIDATOR',
    enclave: 'Frankfurt FR-03',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'FTM',
    entryPrice: 0.62,
    spotPrice: 0.74,
    unrealizedPnl: 0.0,
    pnlPct: 19.35,
    riskRating: 'AA',
    stakingApy: 4.5,
  },
  {
    symbol: 'HBAR',
    name: 'HEDERA GOVERNING COUNCIL HASHGRAPH',
    enclave: 'London LD-03',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'HBAR',
    entryPrice: 0.05,
    spotPrice: 0.06,
    unrealizedPnl: 0.0,
    pnlPct: 20.0,
    riskRating: 'AA',
    stakingApy: 5.1,
  },
  {
    symbol: 'DOGE',
    name: 'DOGECOIN SOVEREIGN SETTLEMENT VAULT',
    enclave: 'Geneva Bunker Beta',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'DOGE',
    entryPrice: 0.1,
    spotPrice: 0.12,
    unrealizedPnl: 0.0,
    pnlPct: 20.0,
    riskRating: 'A+',
  },
  {
    symbol: 'SHIB',
    name: 'SHIBA INU LIQUIDITY RESERVE POT',
    enclave: 'Singapore SG-04',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'SHIB',
    entryPrice: 0.000017,
    spotPrice: 0.000019,
    unrealizedPnl: 0.0,
    pnlPct: 11.76,
    riskRating: 'A+',
  },
  {
    symbol: 'XMR',
    name: 'MONERO CONFIDENTIAL ASSET VAULT',
    enclave: 'Zurich FreePort Sub-Vault',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'XMR',
    entryPrice: 145.0,
    spotPrice: 162.0,
    unrealizedPnl: 0.0,
    pnlPct: 11.72,
    riskRating: 'AA',
  },
  {
    symbol: 'TWT',
    name: 'TRUST WALLET TOKEN GOVERNANCE STAKE',
    enclave: 'Geneva Bunker Alpha',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'TWT',
    entryPrice: 0.95,
    spotPrice: 1.12,
    unrealizedPnl: 0.0,
    pnlPct: 17.89,
    riskRating: 'A+',
    stakingApy: 6.2,
  },
  {
    symbol: 'UNI',
    name: 'UNISWAP V3 DECENTRALIZED PROTOCOL',
    enclave: 'New York NY-04',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'UNI',
    entryPrice: 7.2,
    spotPrice: 8.45,
    unrealizedPnl: 0.0,
    pnlPct: 17.36,
    riskRating: 'AA',
    stakingApy: 4.8,
  },
  {
    symbol: 'AAVE',
    name: 'AAVE SAFETY MODULE LIQUIDITY STAKE',
    enclave: 'London LD-05',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'AAVE',
    entryPrice: 135.0,
    spotPrice: 162.0,
    unrealizedPnl: 0.0,
    pnlPct: 20.0,
    riskRating: 'AA',
    stakingApy: 7.5,
  },
  {
    symbol: 'MKR',
    name: 'MAKER SKY PROTOCOL SURPLUS BUFFER',
    enclave: 'Zurich Node 02',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'MKR',
    entryPrice: 1450.0,
    spotPrice: 1680.0,
    unrealizedPnl: 0.0,
    pnlPct: 15.86,
    riskRating: 'AA',
    stakingApy: 6.9,
  },
  {
    symbol: 'LDO',
    name: 'LIDO DAO STAKING CONSORTIUM CORE',
    enclave: 'Frankfurt FR-04',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'LDO',
    entryPrice: 1.15,
    spotPrice: 1.35,
    unrealizedPnl: 0.0,
    pnlPct: 17.39,
    riskRating: 'AA',
    stakingApy: 4.2,
  },
  {
    symbol: 'ENA',
    name: 'ETHENA SYNTHETIC DOLLAR USDe YIELD',
    enclave: 'Geneva Node 10',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'ENA',
    entryPrice: 0.48,
    spotPrice: 0.58,
    unrealizedPnl: 0.0,
    pnlPct: 20.83,
    riskRating: 'A+',
    stakingApy: 16.4,
  },
  {
    symbol: 'PENDLE',
    name: 'PENDLE INSTITUTIONAL YIELD TOKENIZATION',
    enclave: 'Singapore SG-05',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'PENDLE',
    entryPrice: 3.8,
    spotPrice: 4.55,
    unrealizedPnl: 0.0,
    pnlPct: 19.74,
    riskRating: 'A+',
    stakingApy: 18.2,
  },
  {
    symbol: 'JUP',
    name: 'JUPITER SOLANA LIQUIDITY AGGREGATOR',
    enclave: 'Tokyo TK-03',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'JUP',
    entryPrice: 0.85,
    spotPrice: 1.02,
    unrealizedPnl: 0.0,
    pnlPct: 20.0,
    riskRating: 'AA',
    stakingApy: 8.5,
  },
  {
    symbol: 'PYTH',
    name: 'PYTH ORACLE NETWORK HIGH-PRECISION STAKE',
    enclave: 'Zurich Vault 03',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'PYTH',
    entryPrice: 0.32,
    spotPrice: 0.39,
    unrealizedPnl: 0.0,
    pnlPct: 21.88,
    riskRating: 'AA',
    stakingApy: 6.8,
  },
  {
    symbol: 'ONDO',
    name: 'ONDO SHORT-TERM US TREASURIES (OUSG)',
    enclave: 'New York NY-05',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'ONDO',
    entryPrice: 0.72,
    spotPrice: 0.85,
    unrealizedPnl: 0.0,
    pnlPct: 18.06,
    riskRating: 'AAA',
    stakingApy: 5.15,
  },
  {
    symbol: 'WLD',
    name: 'WORLD NETWORK PROOF-OF-HUMANITY VAULT',
    enclave: 'London LD-06',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'WLD',
    entryPrice: 1.9,
    spotPrice: 2.25,
    unrealizedPnl: 0.0,
    pnlPct: 18.42,
    riskRating: 'A+',
  },
  {
    symbol: 'KAVA',
    name: 'KAVA CROSS-CHAIN LENDING NETWORK',
    enclave: 'Geneva Bunker Alpha',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'KAVA',
    entryPrice: 0.38,
    spotPrice: 0.44,
    unrealizedPnl: 0.0,
    pnlPct: 15.79,
    riskRating: 'AA',
    stakingApy: 9.8,
  },
  {
    symbol: 'MINA',
    name: 'MINA ZERO-KNOWLEDGE LIGHTWEIGHT LEDGER',
    enclave: 'Zurich Alpha 04',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'MINA',
    entryPrice: 0.52,
    spotPrice: 0.61,
    unrealizedPnl: 0.0,
    pnlPct: 17.31,
    riskRating: 'A+',
    stakingApy: 12.1,
  },
  {
    symbol: 'GRT',
    name: 'THE GRAPH BLOCKCHAIN DATA INDEXER',
    enclave: 'Frankfurt FR-05',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'GRT',
    entryPrice: 0.14,
    spotPrice: 0.17,
    unrealizedPnl: 0.0,
    pnlPct: 21.43,
    riskRating: 'A+',
    stakingApy: 7.2,
  },
  {
    symbol: 'ENS',
    name: 'ETHEREUM NAME SERVICE REGISTRY RESERVE',
    enclave: 'Geneva Node 12',
    custodyType: 'SOVEREIGN_CUSTODY',
    custodyLabel: 'Sovereign MPC Cold',
    balance: 0.0,
    unit: 'ENS',
    entryPrice: 17.5,
    spotPrice: 20.8,
    unrealizedPnl: 0.0,
    pnlPct: 18.86,
    riskRating: 'AA',
  },
  {
    symbol: 'DYDX',
    name: 'DYDX COSMOS APPCHAIN SETTLEMENT STAKE',
    enclave: 'Singapore SG-06',
    custodyType: 'STAKING_LOCKUP',
    custodyLabel: 'Staking Validator',
    balance: 0.0,
    unit: 'DYDX',
    entryPrice: 1.05,
    spotPrice: 1.25,
    unrealizedPnl: 0.0,
    pnlPct: 19.05,
    riskRating: 'A+',
    stakingApy: 14.2,
  },
];

export const STOCKS_HOLDINGS_DATA: StockHolding[] = [
  // 1-4: Primary Active Holdings Held by User
  {
    symbol: 'NVDA',
    name: 'NVIDIA CORP DMA BLOCK',
    category: 'Global Tech Infrastructure',
    custodian: 'DTCC / Euroclear CH',
    shares: 4200,
    entryMark: 112.4,
    currentMark: 138.85,
    unrealizedPnl: 111090.0,
    pnlPct: 23.53,
    beta: 1.15,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'MSFT',
    name: 'MICROSOFT CORP DMA SHARES',
    category: 'Enterprise Cloud & AI',
    custodian: 'BNY Mellon Custody',
    shares: 2500,
    entryMark: 395.0,
    currentMark: 442.1,
    unrealizedPnl: 117750.0,
    pnlPct: 11.92,
    beta: 0.88,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'SPACEX',
    name: 'SPACE EXPLORATION TECHNOLOGIES',
    category: 'Aerospace & Starlink SPV',
    custodian: 'Delaware Private SPV III',
    shares: 1000,
    entryMark: 650.0,
    currentMark: 820.0,
    unrealizedPnl: 170000.0,
    pnlPct: 26.15,
    beta: 0.72,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'ANTHROPIC',
    name: 'ANTHROPIC SERIES C NOTES',
    category: 'Foundational AI Research',
    custodian: 'Geneva SPV Series II',
    shares: 500,
    entryMark: 1200.0,
    currentMark: 1480.0,
    unrealizedPnl: 140000.0,
    pnlPct: 23.33,
    beta: 0.65,
    dripEnabled: false,
    isPreIpo: true,
  },

  // 5-50: Expanded Global Stocks Catalog (including AMZN/Amazon, AAPL/Apple, European & Swiss Blue Chips, Pre-IPO SPVs)
  {
    symbol: 'AMZN',
    name: 'AMAZON.COM INC DMA SHARES',
    category: 'Cloud Infrastructure & E-Commerce',
    custodian: 'DTCC / Euroclear CH',
    shares: 0,
    entryMark: 178.5,
    currentMark: 194.2,
    unrealizedPnl: 0.0,
    pnlPct: 8.8,
    beta: 1.12,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'AAPL',
    name: 'APPLE INC DIRECT DMA SHARES',
    category: 'Consumer Hardware & Silicon',
    custodian: 'State Street Global Custody',
    shares: 0,
    entryMark: 215.0,
    currentMark: 232.5,
    unrealizedPnl: 0.0,
    pnlPct: 8.14,
    beta: 0.95,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'GOOGL',
    name: 'ALPHABET INC CLASS A DMA',
    category: 'Autonomous Compute & Search',
    custodian: 'BNY Mellon Institutional',
    shares: 0,
    entryMark: 162.0,
    currentMark: 176.8,
    unrealizedPnl: 0.0,
    pnlPct: 9.14,
    beta: 1.05,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'META',
    name: 'META PLATFORMS INC DMA SHARES',
    category: 'Social Graph & Open-Source AI',
    custodian: 'DTCC / Euroclear CH',
    shares: 0,
    entryMark: 520.0,
    currentMark: 585.4,
    unrealizedPnl: 0.0,
    pnlPct: 12.58,
    beta: 1.22,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'TSLA',
    name: 'TESLA INC GLOBAL EQUITY DMA',
    category: 'Electric Mobility & Robotics',
    custodian: 'JPMorgan Custody London',
    shares: 0,
    entryMark: 210.0,
    currentMark: 248.6,
    unrealizedPnl: 0.0,
    pnlPct: 18.38,
    beta: 1.65,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'BRK.B',
    name: 'BERKSHIRE HATHAWAY CLASS B',
    category: 'Diversified Conglomerate Core',
    custodian: 'Northern Trust Global',
    shares: 0,
    entryMark: 430.0,
    currentMark: 462.1,
    unrealizedPnl: 0.0,
    pnlPct: 7.47,
    beta: 0.62,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'AVGO',
    name: 'BROADCOM INC ENTERPRISE SILICON',
    category: 'Semiconductors & Custom ASICs',
    custodian: 'BNY Mellon Custody',
    shares: 0,
    entryMark: 160.0,
    currentMark: 182.4,
    unrealizedPnl: 0.0,
    pnlPct: 14.0,
    beta: 1.18,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'JPM',
    name: 'JPMORGAN CHASE & CO DMA SHARES',
    category: 'Global Institutional Banking',
    custodian: 'DTCC Direct Participant',
    shares: 0,
    entryMark: 205.0,
    currentMark: 224.8,
    unrealizedPnl: 0.0,
    pnlPct: 9.66,
    beta: 0.85,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'LLY',
    name: 'ELI LILLY AND COMPANY DMA',
    category: 'Biopharmaceutical Innovations',
    custodian: 'Citibank Custody AG',
    shares: 0,
    entryMark: 870.0,
    currentMark: 945.0,
    unrealizedPnl: 0.0,
    pnlPct: 8.62,
    beta: 0.74,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'V',
    name: 'VISA INC CLASS A SHARES',
    category: 'Global Payments Settlement',
    custodian: 'State Street Boston',
    shares: 0,
    entryMark: 268.0,
    currentMark: 284.5,
    unrealizedPnl: 0.0,
    pnlPct: 6.16,
    beta: 0.78,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'UNH',
    name: 'UNITEDHEALTH GROUP INC',
    category: 'Healthcare Benefits & Services',
    custodian: 'Northern Trust Chicago',
    shares: 0,
    entryMark: 540.0,
    currentMark: 575.2,
    unrealizedPnl: 0.0,
    pnlPct: 6.52,
    beta: 0.68,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'XOM',
    name: 'EXXON MOBIL CORP SHARES',
    category: 'Energy & Global Infrastructure',
    custodian: 'BNY Mellon Custody',
    shares: 0,
    entryMark: 112.0,
    currentMark: 120.4,
    unrealizedPnl: 0.0,
    pnlPct: 7.5,
    beta: 0.82,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'MA',
    name: 'MASTERCARD INC CLASS A',
    category: 'Digital Payments Rail',
    custodian: 'JPMorgan Custody London',
    shares: 0,
    entryMark: 460.0,
    currentMark: 492.0,
    unrealizedPnl: 0.0,
    pnlPct: 6.96,
    beta: 0.81,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'JNJ',
    name: 'JOHNSON & JOHNSON COMMON STOCK',
    category: 'Healthcare & Medical Devices',
    custodian: 'State Street Global',
    shares: 0,
    entryMark: 155.0,
    currentMark: 164.2,
    unrealizedPnl: 0.0,
    pnlPct: 5.94,
    beta: 0.55,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'PG',
    name: 'PROCTER & GAMBLE COMPANY',
    category: 'Global Consumer Staples',
    custodian: 'Northern Trust Global',
    shares: 0,
    entryMark: 165.0,
    currentMark: 174.5,
    unrealizedPnl: 0.0,
    pnlPct: 5.76,
    beta: 0.52,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'COST',
    name: 'COSTCO WHOLESALE CORP DMA',
    category: 'Institutional Consumer Logistics',
    custodian: 'Citibank Custody AG',
    shares: 0,
    entryMark: 860.0,
    currentMark: 915.8,
    unrealizedPnl: 0.0,
    pnlPct: 6.49,
    beta: 0.76,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'HD',
    name: 'THE HOME DEPOT INC SHARES',
    category: 'Commercial & Building Retail',
    custodian: 'BNY Mellon Institutional',
    shares: 0,
    entryMark: 375.0,
    currentMark: 402.1,
    unrealizedPnl: 0.0,
    pnlPct: 7.23,
    beta: 0.92,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'ABBV',
    name: 'ABBVIE INC PHARMACEUTICALS',
    category: 'Immunology & Oncology Discovery',
    custodian: 'State Street Boston',
    shares: 0,
    entryMark: 180.0,
    currentMark: 194.5,
    unrealizedPnl: 0.0,
    pnlPct: 8.06,
    beta: 0.64,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'WMT',
    name: 'WALMART INC COMMON STOCK',
    category: 'Global Retail & Logistics Fleet',
    custodian: 'Northern Trust Chicago',
    shares: 0,
    entryMark: 75.0,
    currentMark: 81.2,
    unrealizedPnl: 0.0,
    pnlPct: 8.27,
    beta: 0.58,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'BAC',
    name: 'BANK OF AMERICA CORP DMA',
    category: 'Commercial & Corporate Banking',
    custodian: 'DTCC Direct Participant',
    shares: 0,
    entryMark: 38.0,
    currentMark: 42.4,
    unrealizedPnl: 0.0,
    pnlPct: 11.58,
    beta: 0.94,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'CRM',
    name: 'SALESFORCE INC ENTERPRISE CLOUD',
    category: 'Enterprise CRM & Agentic Cloud',
    custodian: 'BNY Mellon Custody',
    shares: 0,
    entryMark: 280.0,
    currentMark: 308.5,
    unrealizedPnl: 0.0,
    pnlPct: 10.18,
    beta: 1.15,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'NFLX',
    name: 'NETFLIX INC STREAMING DMA',
    category: 'Global Media & Content Networks',
    custodian: 'JPMorgan Custody London',
    shares: 0,
    entryMark: 680.0,
    currentMark: 742.0,
    unrealizedPnl: 0.0,
    pnlPct: 9.12,
    beta: 1.25,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'AMD',
    name: 'ADVANCED MICRO DEVICES DMA',
    category: 'High-Performance GPU & EPYC',
    custodian: 'DTCC / Euroclear CH',
    shares: 0,
    entryMark: 142.0,
    currentMark: 158.4,
    unrealizedPnl: 0.0,
    pnlPct: 11.55,
    beta: 1.48,
    dripEnabled: false,
    isPreIpo: false,
  },
  {
    symbol: 'ORCL',
    name: 'ORACLE CORP CLOUD INFRASTRUCTURE',
    category: 'Enterprise Database & GenAI Compute',
    custodian: 'State Street Global',
    shares: 0,
    entryMark: 150.0,
    currentMark: 172.5,
    unrealizedPnl: 0.0,
    pnlPct: 15.0,
    beta: 1.02,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'ASML',
    name: 'ASML HOLDING NV EXTREME UV',
    category: 'Lithography & Semiconductor Tooling',
    custodian: 'Euroclear Bank Brussels',
    shares: 0,
    entryMark: 760.0,
    currentMark: 835.0,
    unrealizedPnl: 0.0,
    pnlPct: 9.87,
    beta: 1.28,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'TSM',
    name: 'TAIWAN SEMICONDUCTOR MFG CO ADR',
    category: 'Leading-Edge Foundry Fabrication',
    custodian: 'Citibank Custody AG',
    shares: 0,
    entryMark: 175.0,
    currentMark: 198.5,
    unrealizedPnl: 0.0,
    pnlPct: 13.43,
    beta: 1.24,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'SAP',
    name: 'SAP SE ENTERPRISE SOFTWARE',
    category: 'European Enterprise Software',
    custodian: 'Deutsche Bank Custody Frankfurt',
    shares: 0,
    entryMark: 195.0,
    currentMark: 218.4,
    unrealizedPnl: 0.0,
    pnlPct: 12.0,
    beta: 0.88,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'LVMH',
    name: 'LVMH MOET HENNESSY LOUIS VUITTON',
    category: 'Ultra-Luxury Conglomerate',
    custodian: 'BNP Paribas Custody Paris',
    shares: 0,
    entryMark: 620.0,
    currentMark: 685.0,
    unrealizedPnl: 0.0,
    pnlPct: 10.48,
    beta: 0.94,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'NESN',
    name: 'NESTLE SA SWISS BLUE CHIP',
    category: 'Global Food & Nutrition Leader',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 84.0,
    currentMark: 91.2,
    unrealizedPnl: 0.0,
    pnlPct: 8.57,
    beta: 0.45,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'NOVN',
    name: 'NOVARTIS AG REGISTERED SHARES',
    category: 'Swiss Healthcare & Therapeutics',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 92.0,
    currentMark: 101.5,
    unrealizedPnl: 0.0,
    pnlPct: 10.33,
    beta: 0.48,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'ROG',
    name: 'ROCHE HOLDING AG GENUSSCHEIN',
    category: 'Swiss Diagnostics & Oncology',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 255.0,
    currentMark: 278.4,
    unrealizedPnl: 0.0,
    pnlPct: 9.18,
    beta: 0.46,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'UBSG',
    name: 'UBS GROUP AG REGISTERED SHARES',
    category: 'Swiss Global Wealth Management',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 25.5,
    currentMark: 28.9,
    unrealizedPnl: 0.0,
    pnlPct: 13.33,
    beta: 1.08,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'CFR',
    name: 'COMPAGNIE FINANCIERE RICHEMONT',
    category: 'High Horology & Luxury Goods',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 132.0,
    currentMark: 146.5,
    unrealizedPnl: 0.0,
    pnlPct: 10.98,
    beta: 0.98,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'ABBN',
    name: 'ABB LTD SWISS INDUSTRIAL ROBOTICS',
    category: 'Industrial Automation & Electrification',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 46.0,
    currentMark: 51.8,
    unrealizedPnl: 0.0,
    pnlPct: 12.61,
    beta: 0.85,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'ZURN',
    name: 'ZURICH INSURANCE GROUP AG',
    category: 'Commercial Insurance & Reinsurance',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 485.0,
    currentMark: 524.0,
    unrealizedPnl: 0.0,
    pnlPct: 8.04,
    beta: 0.68,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'SREN',
    name: 'SWISS RE LTD REGISTERED SHARES',
    category: 'Global Reinsurance Specialist',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 112.0,
    currentMark: 122.5,
    unrealizedPnl: 0.0,
    pnlPct: 9.38,
    beta: 0.72,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'LONN',
    name: 'LONZA GROUP AG CDMO BIOTECH',
    category: 'Biologics Manufacturing Enclave',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 510.0,
    currentMark: 565.0,
    unrealizedPnl: 0.0,
    pnlPct: 10.78,
    beta: 0.82,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'GIVN',
    name: 'GIVAUDAN SA SPECIALTY FLAVORS',
    category: 'Fine Fragrance & Precision Ingredients',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 3950.0,
    currentMark: 4280.0,
    unrealizedPnl: 0.0,
    pnlPct: 8.35,
    beta: 0.54,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'SIKA',
    name: 'SIKA AG SPECIALTY CHEMICALS',
    category: 'Construction Materials & Sealing',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 255.0,
    currentMark: 282.0,
    unrealizedPnl: 0.0,
    pnlPct: 10.59,
    beta: 0.95,
    dripEnabled: true,
    isPreIpo: false,
  },
  {
    symbol: 'ALC',
    name: 'ALCON INC OPHTHALMIC SURGICAL',
    category: 'Eye Care & Surgical Systems',
    custodian: 'SIX SIS Zurich Custody',
    shares: 0,
    entryMark: 78.0,
    currentMark: 86.5,
    unrealizedPnl: 0.0,
    pnlPct: 10.9,
    beta: 0.75,
    dripEnabled: true,
    isPreIpo: false,
  },

  // Pre-IPO Unicorns & Sovereign SPVs
  {
    symbol: 'OPENAI',
    name: 'OPENAI GLOBAL LLC PRE-IPO SPV',
    category: 'Foundational Artificial General Intelligence',
    custodian: 'Delaware Private SPV IV',
    shares: 0,
    entryMark: 135.0,
    currentMark: 165.0,
    unrealizedPnl: 0.0,
    pnlPct: 22.22,
    beta: 0.7,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'STRIPE',
    name: 'STRIPE INC SECONDARY EQUITY SPV',
    category: 'Global Digital Financial Infrastructure',
    custodian: 'Silicon Valley SPV Series I',
    shares: 0,
    entryMark: 28.0,
    currentMark: 34.5,
    unrealizedPnl: 0.0,
    pnlPct: 23.21,
    beta: 0.85,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'DATABRICKS',
    name: 'DATABRICKS INC LAKEHOUSE PRE-IPO',
    category: 'Unified Data & AI Analytics',
    custodian: 'San Francisco SPV III',
    shares: 0,
    entryMark: 65.0,
    currentMark: 78.2,
    unrealizedPnl: 0.0,
    pnlPct: 20.31,
    beta: 0.82,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'BYTEDANCE',
    name: 'BYTEDANCE LTD OFFSHORE SPV',
    category: 'Algorithmic Content & Video Networks',
    custodian: 'Cayman Institutional Custody',
    shares: 0,
    entryMark: 160.0,
    currentMark: 185.0,
    unrealizedPnl: 0.0,
    pnlPct: 15.63,
    beta: 0.95,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'ANDURIL',
    name: 'ANDURIL INDUSTRIES DEFENSE TECH',
    category: 'Autonomous Defense Hardware & Lattice AI',
    custodian: 'Delaware Private SPV V',
    shares: 0,
    entryMark: 42.0,
    currentMark: 54.0,
    unrealizedPnl: 0.0,
    pnlPct: 28.57,
    beta: 0.65,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'SCALEAI',
    name: 'SCALE AI INC DATA ACCELERATOR',
    category: 'Enterprise RLHF & Training Pipelines',
    custodian: 'Delaware Private SPV VI',
    shares: 0,
    entryMark: 32.0,
    currentMark: 39.5,
    unrealizedPnl: 0.0,
    pnlPct: 23.44,
    beta: 0.78,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'RIPPLE',
    name: 'RIPPLE LABS PRE-IPO EQUITY',
    category: 'Institutional Cross-Border Liquidity',
    custodian: 'Geneva SPV Series IV',
    shares: 0,
    entryMark: 45.0,
    currentMark: 52.0,
    unrealizedPnl: 0.0,
    pnlPct: 15.56,
    beta: 0.88,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'NEURALINK',
    name: 'NEURALINK CORP BRAIN INTERFACE',
    category: 'High-Bandwidth Neural Engineering',
    custodian: 'Austin Private SPV I',
    shares: 0,
    entryMark: 85.0,
    currentMark: 105.0,
    unrealizedPnl: 0.0,
    pnlPct: 23.53,
    beta: 0.6,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'DISCORD',
    name: 'DISCORD INC REAL-TIME VOICE SPV',
    category: 'Community & High-Bandwidth Social',
    custodian: 'Silicon Valley SPV II',
    shares: 0,
    entryMark: 52.0,
    currentMark: 59.5,
    unrealizedPnl: 0.0,
    pnlPct: 14.42,
    beta: 0.9,
    dripEnabled: false,
    isPreIpo: true,
  },
  {
    symbol: 'CANVA',
    name: 'CANVA PTY LTD DESIGN UNICORN',
    category: 'Collaborative Visual Communication',
    custodian: 'Sydney SPV Offshore Trust',
    shares: 0,
    entryMark: 980.0,
    currentMark: 1140.0,
    unrealizedPnl: 0.0,
    pnlPct: 16.33,
    beta: 0.8,
    dripEnabled: false,
    isPreIpo: true,
  },
];

export const LEVEL_2_ORDER_BOOK: { bids: OrderBookEntry[]; asks: OrderBookEntry[] } = {
  bids: [
    { price: 138.82, size: 2400, total: 2400, depthPct: 75 },
    { price: 138.8, size: 3100, total: 5500, depthPct: 88 },
    { price: 138.78, size: 1800, total: 7300, depthPct: 62 },
    { price: 138.75, size: 5200, total: 12500, depthPct: 95 },
    { price: 138.72, size: 1400, total: 13900, depthPct: 45 },
  ],
  asks: [
    { price: 138.85, size: 1900, total: 1900, depthPct: 68 },
    { price: 138.88, size: 2800, total: 4700, depthPct: 82 },
    { price: 138.9, size: 4100, total: 8800, depthPct: 92 },
    { price: 138.94, size: 1200, total: 10000, depthPct: 40 },
    { price: 138.98, size: 3500, total: 13500, depthPct: 85 },
  ],
};

export const INITIAL_DCA_SCHEDULES: DcaScheduleItem[] = [
  {
    id: 'dca-btc-01',
    asset: 'BTC',
    frequency: 'WEEKLY',
    amountUsd: 25000,
    sourceAccount: 'USD Fedwire Treasury',
    nextExecution: 'In 3 days (Monday 00:00 UTC)',
    active: true,
  },
  {
    id: 'dca-eth-02',
    asset: 'ETH',
    frequency: 'MONTHLY',
    amountUsd: 50000,
    sourceAccount: 'USDC Cash Pot',
    nextExecution: 'In 14 days (1st of month)',
    active: true,
  },
  {
    id: 'dca-sol-03',
    asset: 'SOL',
    frequency: 'DAILY',
    amountUsd: 5000,
    sourceAccount: 'CHF SIC Cash Pot',
    nextExecution: 'In 8 hours',
    active: false,
  },
];

export const WALLET_TRANSACTIONS_DATA: WalletTransaction[] = [
  {
    id: 'tx-9941',
    timestamp: 'Today, 14:02 CET',
    vertical: 'CASH',
    type: 'SWEEP',
    description: 'Auto-Sweep Idle Cash into 5.20% Money Market',
    amountUsd: 48500.0,
    status: 'CLEARED',
    reference: 'MMF-SWEEP-0941',
  },
  {
    id: 'tx-9940',
    timestamp: 'Yesterday, 18:24 CET',
    vertical: 'CRYPTO',
    type: 'SWAP',
    description: 'Executed Sovereign OTC Swap: 50,000 USDC -> 0.559 BTC',
    amountUsd: 50000.0,
    status: 'CLEARED',
    reference: 'OTC-FIX-7721',
  },
  {
    id: 'tx-9939',
    timestamp: '12 Sep 2026',
    vertical: 'STOCKS',
    type: 'DIVIDEND',
    description: 'NVIDIA Q3 Dividend Credit (Auto-DRIP Reinvested)',
    amountUsd: 1420.0,
    status: 'CLEARED',
    reference: 'DIV-NVDA-8812',
  },
  {
    id: 'tx-9938',
    timestamp: '10 Sep 2026',
    vertical: 'REAL_ESTATE',
    type: 'DIVIDEND',
    description: 'Zurich Prime Commercial Net Monthly Rental Distribution',
    amountUsd: 37500.0,
    status: 'CLEARED',
    reference: 'SPV-RENT-4401',
  },
  {
    id: 'tx-9937',
    timestamp: '08 Sep 2026',
    vertical: 'CASH',
    type: 'DEPOSIT',
    description: 'Fedwire Inbound Escrow Clearing via JPMorgan',
    amountUsd: 500000.0,
    status: 'CLEARED',
    reference: 'FEDWIRE-49120',
  },
];
